SectionVerb {
        EnableSequence [
                cset "name='DACL Volume' 137"
                cset "name='DACR Volume' 137"
                cset "name='DAC Gain' 0"
                cset "name='HPOUT Gain' 3"
                cset "name='HPOUT Switch' on"
                cset "name='SPK Switch' off"
                cset "name='LINEOUTL Switch' off"
                cset "name='LINEOUTR Switch' off"
                cset "name='MIC1 Switch' off"
                cset "name='MIC2 Switch' off"
                cset "name='MIC3 Switch' off"
                cset "name='MIC4 Switch' on"
                cset "name='ADC2 Input Src Mux' MIC4"
                cset "name='ADC2 Data Select Mux' ADC2_Input"
                cset "name='ADC2 Gain' 14"
                cset "name='ADC2 Volume' 219"
                cset "name='AIF TX2 Mux' ADC2_Data"
                cset "name='ADC1 Volume' 0"
                cset "name='ADC1 Gain' 0"
        ]

        DisableSequence [
                cset "name='SPK Switch' off"
                cset "name='HPOUT Switch' off"
                cset "name='MIC4 Switch' off"
        ]
}

SectionDevice."Headphones" {
        Comment "Headphones"

        EnableSequence [
                cset "name='SPK Switch' off"
                cset "name='HPOUT Switch' on"
                cset "name='HPOUT Gain' 3"
                cset "name='DACL Volume' 137"
                cset "name='DACR Volume' 137"
        ]

        DisableSequence [
                cset "name='HPOUT Switch' off"
                cset "name='SPK Switch' off"
        ]

        Value {
                PlaybackVolume "HPOUT Gain"
                PlaybackPriority 200
                PlaybackChannels "2"
                PlaybackPCM "hw:${CardId},0"
                JackControl "HP Jack"
        }
}

SectionDevice."Headset Mic" {
        Comment "Headset Mic"

        EnableSequence [
                cset "name='MIC4 Switch' on"
                cset "name='ADC2 Input Src Mux' MIC4"
                cset "name='ADC2 Data Select Mux' ADC2_Input"
                cset "name='ADC2 Gain' 14"
                cset "name='ADC2 Volume' 219"
                cset "name='AIF TX2 Mux' ADC2_Data"
        ]

        DisableSequence [
                cset "name='MIC4 Switch' off"
                cset "name='ADC2 Gain' 0"
        ]

        Value {
                CapturePriority 200
                CapturePCM "hw:${CardId},0"
                CaptureChannels "1"
        }
}
